import { describe, it, expect } from 'vitest';
import { loadFixture, SIMPLE_PDF, WITH_FORMS_PDF } from '../helpers';
import { flattenForms } from '../../src/forms/flatten-forms';
import { openDocument, closeDocument } from '../../src/engine/document-handle';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeBuffer(fixture: string): Buffer {
  return Buffer.from(loadFixture(fixture));
}

/**
 * Hand-craft a minimal but valid PDF whose single page invokes a Form XObject
 * (`/Fm0 Do`). None of the bundled fixtures contain a form XObject (they are
 * generated by the engine, which doesn't emit them), so we build one to
 * exercise the `count > 0` path. The XObject draws "Hi" with Helvetica.
 */
function buildFormXObjectPdf(): Buffer {
  const objects: string[] = [];
  objects.push(`<< /Type /Catalog /Pages 2 0 R >>`);
  objects.push(`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`);
  objects.push(
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] ` +
      `/Resources << /XObject << /Fm0 5 0 R >> >> /Contents 4 0 R >>`,
  );
  const content = `q /Fm0 Do Q`;
  objects.push(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);
  const formContent = `BT /F1 24 Tf 20 80 Td (Hi) Tj ET`;
  objects.push(
    `<< /Type /XObject /Subtype /Form /FormType 1 /BBox [0 0 200 200] ` +
      `/Resources << /Font << /F1 6 0 R >> >> /Length ${formContent.length} >>\n` +
      `stream\n${formContent}\nendstream`,
  );
  objects.push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);

  let pdf = `%PDF-1.7\n`;
  const offsets: number[] = [];
  for (let i = 0; i < objects.length; i++) {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xrefPos = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += `0000000000 65535 f \n`;
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefPos}\n%%EOF`;
  return Buffer.from(pdf, 'latin1');
}

// ---------------------------------------------------------------------------
// flattenForms — no-op path (form-less PDFs)
// ---------------------------------------------------------------------------

describe('flattenForms', () => {
  it('returns count 0 and the original bytes unchanged for a form-less PDF', async () => {
    const source = loadFixture(SIMPLE_PDF); // Uint8Array, no form XObjects
    const result = await flattenForms(source);

    expect(result.count).toBe(0);
    // Same reference, never re-serialised → byte-identical to the source.
    expect(result.bytes).toBe(source);
  });

  it('does not re-serialise (byte-identical) when the AcroForm fixture has no form XObjects', async () => {
    // with-forms.pdf has AcroForm *widgets* but no Form XObjects, so flatten
    // inlines 0 and the document must come back untouched.
    const source = loadFixture(WITH_FORMS_PDF);
    const before = Buffer.from(source);
    const result = await flattenForms(source);

    expect(result.count).toBe(0);
    expect(Buffer.from(result.bytes)).toEqual(before);
  });

  it('accepts a Buffer input and round-trips it unchanged when form-less', async () => {
    const source = makeBuffer(SIMPLE_PDF);
    const result = await flattenForms(source);

    expect(result.count).toBe(0);
    expect(result.bytes).toBe(source);
  });

  // -------------------------------------------------------------------------
  // flattenForms — flatten path (form XObjects present)
  // -------------------------------------------------------------------------

  it('inlines form XObjects and reports a positive count', async () => {
    const source = buildFormXObjectPdf();
    const result = await flattenForms(source);

    expect(result.count).toBeGreaterThan(0);
    // A flatten happened → new bytes were produced (not the input reference).
    expect(result.bytes).not.toBe(source);
    expect(result.bytes.length).toBeGreaterThan(0);
  });

  it('produces a valid PDF (loadable by the engine) after flattening', async () => {
    const source = buildFormXObjectPdf();
    const result = await flattenForms(source);

    const handle = await openDocument(Buffer.from(result.bytes));
    expect(handle.pageCount).toBeGreaterThan(0);
    closeDocument(handle);
  });

  it('is idempotent — re-flattening an already-flattened PDF inlines 0', async () => {
    const source = buildFormXObjectPdf();
    const first = await flattenForms(source);
    expect(first.count).toBeGreaterThan(0);

    const second = await flattenForms(first.bytes);
    expect(second.count).toBe(0);
    // Second pass is a no-op → returns the (already-flattened) bytes unchanged.
    expect(second.bytes).toBe(first.bytes);
  });
});
