"""
Unit tests for FontExtractionService.

Covers: embedded TTF extraction, Base14 non-embedded fonts, subset detection,
font_id determinism, and binary format detection via magic bytes.

Fixtures:
  tests/unit/services/fixtures/sample_embedded_font.pdf  — PDF with one
    embedded TrueType font (ABCDEF+DejaVuSans).
  tests/unit/services/fixtures/sample_base14_only.pdf    — PDF referencing
    Helvetica (Base14) without embedding.
"""

import hashlib
import io
import struct
from pathlib import Path

import pikepdf
import pytest

from app.services.font_extraction_service import (
    FontDictContext,
    FontExtractionService,
)

# OTS-required tables for any browser-loadable sfnt. TrueType also needs
# glyf+loca; CFF-OTF needs the "CFF " table — both are checked separately.
_OTS_REQUIRED = {"cmap", "head", "hhea", "hmtx", "maxp", "name", "OS/2", "post"}

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="module")
def service() -> FontExtractionService:
    return FontExtractionService()


@pytest.fixture(scope="module")
def embedded_pdf_bytes() -> bytes:
    return (FIXTURES_DIR / "sample_embedded_font.pdf").read_bytes()


@pytest.fixture(scope="module")
def base14_pdf_bytes() -> bytes:
    return (FIXTURES_DIR / "sample_base14_only.pdf").read_bytes()


@pytest.fixture(scope="module")
def subset_no_cmap_pdf_bytes() -> bytes:
    """
    A real Type0/CIDFontType2 PDF whose embedded subset TrueType program
    lacks a `cmap` table (the exact shape of the failing
    "KWVFOU+TimesNewRoman,Bold" / "ECYBWA+TimesNewRoman" subset fonts).

    The PDF carries an Identity-H encoding, /CIDToGIDMap /Identity and a
    /ToUnicode CMap mapping CID(=GID) → Unicode, so the repair can synthesise
    a valid cmap. Generated by tests/unit/services/fixtures/_gen_subset_no_cmap.py.
    """
    return (FIXTURES_DIR / "subset_no_cmap_font.pdf").read_bytes()


# ---------------------------------------------------------------------------
# Tests: extract_fonts
# ---------------------------------------------------------------------------


class TestExtractFonts:
    """Tests for FontExtractionService.extract_fonts."""

    def test_extract_fonts_with_embedded_ttf(
        self, service: FontExtractionService, embedded_pdf_bytes: bytes
    ) -> None:
        """PDF with embedded TrueType font → is_embedded=True, format=ttf."""
        fonts = service.extract_fonts(embedded_pdf_bytes)

        assert len(fonts) >= 1, "Expected at least one font in the fixture PDF"

        embedded = [f for f in fonts if f.metadata.is_embedded]
        assert embedded, "Expected at least one embedded font"

        font = embedded[0]
        assert font.metadata.is_embedded is True
        assert font.metadata.format == "ttf"
        assert font.data is not None
        assert len(font.data) > 0
        assert font.metadata.subtype in ("TrueType", "CIDFontType2", "Type0")

    def test_extract_fonts_base14_only(
        self, service: FontExtractionService, base14_pdf_bytes: bytes
    ) -> None:
        """PDF with Base14 Helvetica reference → is_embedded=False, data=None."""
        fonts = service.extract_fonts(base14_pdf_bytes)

        assert len(fonts) >= 1, "Expected at least one font entry"

        helvetica_fonts = [
            f for f in fonts if "Helvetica" in (f.metadata.original_name or "")
        ]
        assert helvetica_fonts, "Expected Helvetica font entry"

        font = helvetica_fonts[0]
        assert font.metadata.is_embedded is False
        assert font.data is None

    def test_extract_fonts_subset_detection(
        self, service: FontExtractionService, embedded_pdf_bytes: bytes
    ) -> None:
        """Font with ABCDEF+ prefix in postscript_name → is_subset=True."""
        fonts = service.extract_fonts(embedded_pdf_bytes)

        subset_fonts = [f for f in fonts if f.metadata.is_subset]
        assert subset_fonts, (
            "Expected at least one subset font (ABCDEF+DejaVuSans) in fixture"
        )
        font = subset_fonts[0]
        assert font.metadata.postscript_name is not None
        assert font.metadata.postscript_name.startswith("ABCDEF+")

    def test_extract_fonts_returns_deduplicated_list(
        self, service: FontExtractionService, embedded_pdf_bytes: bytes
    ) -> None:
        """The same font referenced on multiple pages must appear only once."""
        fonts = service.extract_fonts(embedded_pdf_bytes)
        font_ids = [f.metadata.font_id for f in fonts]
        assert len(font_ids) == len(set(font_ids)), "Duplicate font_ids found"

    def test_extract_fonts_raises_on_invalid_pdf(
        self, service: FontExtractionService
    ) -> None:
        """Garbage bytes should raise ValueError."""
        with pytest.raises(ValueError, match="Cannot open PDF"):
            service.extract_fonts(b"not a pdf at all")


# ---------------------------------------------------------------------------
# Tests: compute_font_id
# ---------------------------------------------------------------------------


class TestComputeFontId:
    """Tests for FontExtractionService.compute_font_id (static method)."""

    def test_compute_font_id_deterministic(self) -> None:
        """Same input must always produce the same font_id."""
        fid1 = FontExtractionService.compute_font_id("ABCDEF+Calibri", "TrueType")
        fid2 = FontExtractionService.compute_font_id("ABCDEF+Calibri", "TrueType")
        assert fid1 == fid2

    def test_compute_font_id_length(self) -> None:
        """font_id must be exactly 16 hex characters."""
        fid = FontExtractionService.compute_font_id("Arial", "TrueType")
        assert len(fid) == 16
        assert all(c in "0123456789abcdef" for c in fid)

    def test_compute_font_id_differs_by_subtype(self) -> None:
        """Same name but different subtype → different font_id."""
        fid_tt = FontExtractionService.compute_font_id("Arial", "TrueType")
        fid_t1 = FontExtractionService.compute_font_id("Arial", "Type1")
        assert fid_tt != fid_t1

    def test_compute_font_id_none_name(self) -> None:
        """None postscript_name falls back to 'unknown', must not raise."""
        fid = FontExtractionService.compute_font_id(None, "TrueType")
        expected = hashlib.sha256(b"unknown|TrueType").hexdigest()[:16]
        assert fid == expected


# ---------------------------------------------------------------------------
# Tests: detect_format
# ---------------------------------------------------------------------------


class TestDetectFormat:
    """Tests for FontExtractionService.detect_format (static method)."""

    def test_detect_format_ttf_magic_00010000(self) -> None:
        """Magic bytes \\x00\\x01\\x00\\x00 → 'ttf'."""
        data = b"\x00\x01\x00\x00" + b"\x00" * 100
        result = FontExtractionService.detect_format(data, "TrueType")
        assert result == "ttf"

    def test_detect_format_ttf_magic_true(self) -> None:
        """Magic bytes 'true' → 'ttf'."""
        data = b"true" + b"\x00" * 100
        result = FontExtractionService.detect_format(data, "TrueType")
        assert result == "ttf"

    def test_detect_format_otf(self) -> None:
        """Magic bytes 'OTTO' → 'otf'."""
        data = b"OTTO" + b"\x00" * 100
        result = FontExtractionService.detect_format(data, "CIDFontType2")
        assert result == "otf"

    def test_detect_format_cff_via_subtype_type1c(self) -> None:
        """Subtype 'Type1C' without OTF/TTF magic → 'cff'."""
        data = b"\x01\x00" + b"\x00" * 100  # no OTF/TTF magic
        result = FontExtractionService.detect_format(data, "Type1C")
        assert result == "cff"

    def test_detect_format_cff_via_subtype_cidtype0c(self) -> None:
        """Subtype 'CIDFontType0C' without magic → 'cff'."""
        data = b"\x01\x00" + b"\x00" * 100
        result = FontExtractionService.detect_format(data, "CIDFontType0C")
        assert result == "cff"

    def test_detect_format_none_on_empty_bytes(self) -> None:
        """None or empty bytes → None."""
        assert FontExtractionService.detect_format(None, "TrueType") is None
        assert FontExtractionService.detect_format(b"", "TrueType") is None

    def test_detect_format_unknown_returns_none(self) -> None:
        """Unrecognised magic + unknown subtype → None."""
        data = b"\xDE\xAD\xBE\xEF" + b"\x00" * 100
        result = FontExtractionService.detect_format(data, "Unknown")
        assert result is None


# ---------------------------------------------------------------------------
# Tests: get_mime_type & encode_base64
# ---------------------------------------------------------------------------


class TestHelpers:
    def test_get_mime_type_ttf(self) -> None:
        assert FontExtractionService.get_mime_type("ttf") == "font/ttf"

    def test_get_mime_type_otf(self) -> None:
        assert FontExtractionService.get_mime_type("otf") == "font/otf"

    def test_get_mime_type_cff(self) -> None:
        # CFF is served as font/otf (same container for browser compatibility)
        assert FontExtractionService.get_mime_type("cff") == "font/otf"

    def test_get_mime_type_fallback(self) -> None:
        assert (
            FontExtractionService.get_mime_type("unknown")
            == "application/octet-stream"
        )

    def test_encode_base64_roundtrip(self) -> None:
        import base64

        data = b"\x00\x01\x00\x00" + b"hello world"
        encoded = FontExtractionService.encode_base64(data)
        assert base64.b64decode(encoded) == data


# ---------------------------------------------------------------------------
# Tests: cmap synthesis on a broken-cmap subset font (the real bug)
# ---------------------------------------------------------------------------

# fontTools is required for the OTS repair; skip if unavailable.
fontTools = pytest.importorskip("fontTools")
from fontTools.ttLib import TTFont as _TTFont  # noqa: E402


def _load_repaired(font_bytes: bytes) -> _TTFont:
    """Parse repaired font bytes back with fontTools."""
    return _TTFont(io.BytesIO(font_bytes))


def _cmap_mapping(tt: _TTFont) -> dict[int, str]:
    """Return the best Unicode cmap as {codepoint: glyphname}."""
    return tt["cmap"].getBestCmap()


class TestBrokenCmapRepair:
    """
    End-to-end: a PDF subset font whose embedded program has NO cmap must be
    served back as an OTS-valid sfnt with a synthesised, non-empty cmap.
    """

    def test_extracted_font_has_all_ots_required_tables(
        self,
        service: FontExtractionService,
        subset_no_cmap_pdf_bytes: bytes,
    ) -> None:
        fonts = service.extract_fonts(subset_no_cmap_pdf_bytes)
        embedded = [f for f in fonts if f.data and f.metadata.format in ("ttf", "otf")]
        assert embedded, "Expected an embedded TTF/OTF in the fixture"

        tt = _load_repaired(embedded[0].data)
        present = set(tt.keys())
        missing = _OTS_REQUIRED - present
        assert not missing, f"Repaired font missing OTS-required tables: {missing}"
        # TrueType outlines require glyf + loca.
        assert "glyf" in present and "loca" in present

    def test_repaired_font_has_nonempty_cmap(
        self,
        service: FontExtractionService,
        subset_no_cmap_pdf_bytes: bytes,
    ) -> None:
        fonts = service.extract_fonts(subset_no_cmap_pdf_bytes)
        embedded = [f for f in fonts if f.data and f.metadata.format in ("ttf", "otf")]
        tt = _load_repaired(embedded[0].data)

        assert FontExtractionService._cmap_is_valid(tt), (
            "Repaired font cmap is missing or empty"
        )
        cmap = _cmap_mapping(tt)
        assert len(cmap) > 0, "Repaired cmap has zero entries"

    def test_repaired_cmap_maps_run_unicode_to_real_glyphs(
        self,
        service: FontExtractionService,
        subset_no_cmap_pdf_bytes: bytes,
    ) -> None:
        """
        The synthesised cmap must map the run's Unicode codepoints (recovered
        from /ToUnicode) to glyph names that exist in the font's glyph order,
        so the browser draws the ORIGINAL outline rather than a fallback box.
        """
        fonts = service.extract_fonts(subset_no_cmap_pdf_bytes)
        embedded = [f for f in fonts if f.data and f.metadata.format in ("ttf", "otf")]
        tt = _load_repaired(embedded[0].data)
        cmap = _cmap_mapping(tt)
        glyph_order = set(tt.getGlyphOrder())

        # The fixture renders "Hello World" → at minimum these chars resolve.
        for ch in "Helo Wrd":
            cp = ord(ch)
            assert cp in cmap, f"codepoint U+{cp:04X} ({ch!r}) missing from cmap"
            assert cmap[cp] in glyph_order, (
                f"cmap points U+{cp:04X} at unknown glyph {cmap[cp]!r}"
            )

    def test_raw_embedded_program_genuinely_lacks_cmap(
        self,
        subset_no_cmap_pdf_bytes: bytes,
    ) -> None:
        """Guard: prove the fixture's raw embedded font truly has no cmap."""
        pdf = pikepdf.Pdf.open(io.BytesIO(subset_no_cmap_pdf_bytes))
        found_raw_without_cmap = False
        for page in pdf.pages:
            font_dict = dict(page.Resources.Font)
            for _name, font_obj in font_dict.items():
                d = dict(font_obj)
                inner = dict(dict(d["/DescendantFonts"][0]))
                desc = dict(inner["/FontDescriptor"])
                raw = bytes(desc["/FontFile2"].read_bytes())
                tt = _TTFont(io.BytesIO(raw))
                if "cmap" not in tt:
                    found_raw_without_cmap = True
        assert found_raw_without_cmap, (
            "Fixture is invalid: its embedded font already has a cmap"
        )


# ---------------------------------------------------------------------------
# Tests: cmap-synthesis helpers (no PDF fixture required)
# ---------------------------------------------------------------------------


class TestCmapSynthesisHelpers:
    """Unit tests for the cmap-synthesis building blocks."""

    def test_parse_differences(self) -> None:
        arr = pikepdf.Array(
            [
                65,
                pikepdf.Name("/A"),
                pikepdf.Name("/B"),
                97,
                pikepdf.Name("/a"),
            ]
        )
        result = FontExtractionService._parse_differences(arr)
        assert result == {65: "A", 66: "B", 97: "a"}

    def test_parse_cid_to_gid_identity_bytes(self) -> None:
        # cid 0 -> gid 0 (skipped), cid 1 -> gid 5, cid 2 -> gid 9
        raw = struct.pack(">HHH", 0, 5, 9)
        result = FontExtractionService._parse_cid_to_gid(raw)
        assert result == {1: 5, 2: 9}

    def test_parse_to_unicode_bfchar(self) -> None:
        cmap = (
            b"begincmap\n"
            b"1 beginbfchar\n<0003> <0041>\nendbfchar\n"
            b"endcmap\n"
        )
        result = FontExtractionService._parse_to_unicode_cmap(cmap)
        assert result.get(3) == "A"

    def test_parse_to_unicode_bfrange_scalar(self) -> None:
        cmap = (
            b"begincmap\n"
            b"1 beginbfrange\n<0010> <0012> <0041>\nendbfrange\n"
            b"endcmap\n"
        )
        result = FontExtractionService._parse_to_unicode_cmap(cmap)
        assert result.get(0x10) == "A"
        assert result.get(0x11) == "B"
        assert result.get(0x12) == "C"

    def test_parse_to_unicode_bfrange_array(self) -> None:
        cmap = (
            b"begincmap\n"
            b"1 beginbfrange\n<0001> <0002> [<0048> <0049>]\nendbfrange\n"
            b"endcmap\n"
        )
        result = FontExtractionService._parse_to_unicode_cmap(cmap)
        assert result.get(1) == "H"
        assert result.get(2) == "I"

    def test_glyph_name_to_unicode_named(self) -> None:
        assert FontExtractionService._glyph_name_to_unicode("A") == 0x41
        assert FontExtractionService._glyph_name_to_unicode("space") == 0x20

    def test_glyph_name_to_unicode_uni_prefix(self) -> None:
        assert FontExtractionService._glyph_name_to_unicode("uni00E9") == 0xE9

    def test_glyph_name_to_unicode_unresolvable(self) -> None:
        assert FontExtractionService._glyph_name_to_unicode(".notdef") is None
        assert FontExtractionService._glyph_name_to_unicode("g123") is None

    def test_base_encoding_winansi(self) -> None:
        tbl = FontExtractionService._base_encoding_table("WinAnsiEncoding")
        assert tbl is not None
        assert tbl[0x41] == 0x41  # 'A'
        assert tbl[0x80] == 0x20AC  # euro sign in cp1252

    def test_base_encoding_unknown_returns_none(self) -> None:
        assert FontExtractionService._base_encoding_table("Nonsense") is None
        assert FontExtractionService._base_encoding_table(None) is None

    def test_build_unicode_to_glyphname_from_differences(self) -> None:
        # glyph order: code==gid for a dense subset
        glyph_order = [".notdef", "A", "B"]
        ctx = FontDictContext(differences={1: "A", 2: "B"})
        mapping = FontExtractionService._build_unicode_to_glyphname(
            ctx, glyph_order, existing_cmap=None
        )
        assert mapping == {0x41: "A", 0x42: "B"}

    def test_build_unicode_to_glyphname_from_to_unicode_identity_cid(self) -> None:
        glyph_order = [".notdef", "H", "i"]
        ctx = FontDictContext(
            is_composite=True,
            cid_to_gid="Identity",
            to_unicode={1: "H", 2: "i"},
        )
        mapping = FontExtractionService._build_unicode_to_glyphname(
            ctx, glyph_order, existing_cmap=None
        )
        assert mapping == {ord("H"): "H", ord("i"): "i"}

    def test_make_cmap_table_returns_none_on_empty(self) -> None:
        assert FontExtractionService._make_cmap_table({}) is None

    def test_make_cmap_table_format4_only_for_bmp(self) -> None:
        cmap = FontExtractionService._make_cmap_table({0x41: "A"})
        assert cmap is not None
        formats = {sub.format for sub in cmap.tables}
        assert formats == {4}

    def test_make_cmap_table_adds_format12_for_supplementary(self) -> None:
        cmap = FontExtractionService._make_cmap_table({0x1F600: "emoji"})
        assert cmap is not None
        formats = {sub.format for sub in cmap.tables}
        assert 12 in formats

    def test_cmap_is_valid_rejects_mac_only_subtable(self) -> None:
        """
        Regression (s1106.pdf): a font whose ONLY cmap subtable is (1,0)
        Macintosh is NOT browser-loadable — Chrome's OTS rejects it with
        "cmap: no supported subtables were found", rendering text as tofu.
        _cmap_is_valid must report such a font BROKEN so a Windows-Unicode
        (3,1) gets synthesised; _existing_cmap_dict must skip the Mac byte-code
        mapping so it never poisons the synthesised cmap with codes >= 0x80.
        """
        from fontTools.ttLib import TTFont, newTable
        from fontTools.ttLib.tables import _c_m_a_p as cmap_mod

        def font_with(subtables: list) -> TTFont:  # noqa: ANN401
            font = TTFont()
            cmap = newTable("cmap")
            cmap.tableVersion = 0
            cmap.tables = subtables
            font["cmap"] = cmap
            return font

        mac = cmap_mod.cmap_format_6(6)
        mac.platformID, mac.platEncID, mac.language = 1, 0, 0
        mac.cmap = {0x41: "A", 0x80: "Euro"}

        win = cmap_mod.cmap_format_4(4)
        win.platformID, win.platEncID, win.language = 3, 1, 0
        win.cmap = {0x41: "A"}

        # Mac-only → invalid (forces synthesis) + Mac byte mapping skipped.
        mac_only = font_with([mac])
        assert FontExtractionService._cmap_is_valid(mac_only) is False
        assert FontExtractionService._existing_cmap_dict(mac_only) is None

        # Windows-Unicode subtable present → valid + readable as Unicode.
        with_unicode = font_with([win])
        assert FontExtractionService._cmap_is_valid(with_unicode) is True
        assert FontExtractionService._existing_cmap_dict(with_unicode) == {0x41: "A"}
